name: Performance test

on:
  workflow_dispatch:

jobs:
  performance-test:
    name: Performance test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: main
        
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          path: clojure-lsp
          repository: clojure-lsp/clojure-lsp

      - run: echo "skip=false" >> $GITHUB_ENV
          
      - name: Prepare java
        if: env.skip != true
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install Clojure
        if: env.skip != true
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.1013'
          bb: '0.9.161'

      - name: Run tests
        run: |
          (cd main && clojure -M:test && clojure -X:jmh :output '"result-HEAD.clj"' :status true)
          (cd clojure-lsp && git checkout HEAD~1)
          (cd main && clojure -M:test && clojure -X:jmh :output '"result-HEAD-1.clj"' :status true)

      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: |
            main/result-HEAD.clj
            main/result-HEAD-1.clj