name: Performance test

on:
  workflow_dispatch:

jobs:
  performance-test:
    name: Performance test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: main
        
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
          path: clojure-lsp
          repository: clojure-lsp/clojure-lsp
          
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.1013'
          bb: '0.9.161'

      - run: (cd clojure-lsp && sh ../main/scripts/github-envs.sh >> $GITHUB_ENV && cat $GITHUB_ENV)

      - name: Run tests
        run: |
          (cd clojure-lsp && git checkout $BASELINE_COMMIT)
          (cd main && clojure -M:test && clojure -X:jmh :output '"result-BASELINE.clj"' :status true)
          (cd clojure-lsp && git checkout $MEASURED_COMMIT)
          (cd main && clojure -M:test && clojure -X:jmh :output '"result-MEASURED.clj"' :status true)

      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: |
            main/result-HEAD.clj
            main/result-HEAD-1.clj